baseURL = 'https://cafebeef1.github.io/'
languageCode = 'zh-cn'
title = "cafebeef1's blog"
theme = "anubis2"

[params]
    subtitle = "行到水穷处, 坐看云起时."
[params.contact]
    email = "cafebeef1@gmail.com"
[params.utterances]
    owner = "cafebeef1"
    repo = "cafebeef1.github.io"

[menus]
[[menus.main]]
name = "Posts"
pageRef = '/posts'
weight = 15
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10
[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 20
